services:
  web:
    container_name: web
    depends_on:
      - server
    restart: always
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
      args:
        PACKAGE_NAME: '@template-turborepo-vue/web'
    networks:
      - app-network
    ports:
      - 5173:80
    volumes:
      - ./docker/nginx/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf:ro
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro

  server:
    container_name: server
    env_file:
      - ./apps/server/.env
    restart: always
    build:
      context: .
      dockerfile: ./apps/server/Dockerfile
      args:
        PACKAGE_NAME: '@template-turborepo-vue/server'
    networks:
      - app-network
    ports:
      - 5183:5183

networks:
  app-network:
    driver: bridge
