services:
  web:
    image: template-turborepo-vue/web:${TAG:-latest}
    container_name: web
    depends_on:
      - server
    restart: always
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
      args:
        PACKAGE_NAME: '@template-turborepo-vue/web'
    networks:
      - app-network
    ports:
      - 5173:80
    # volumes:
    #   - ./apps/web/nginx/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf:ro
    #   - ./apps/web/nginx/conf.d:/etc/nginx/conf.d:ro
    #   - logs:/var/log/nginx
    #   - logs:/usr/local/openresty/nginx/logs
    #   - /var/run/openresty

  server:
    image: template-turborepo-vue/server:${TAG:-latest}
    container_name: server
    env_file:
      - ./apps/server/.env
    restart: always
    build:
      context: .
      dockerfile: ./apps/server/Dockerfile
      args:
        PACKAGE_NAME: '@template-turborepo-vue/server'
    networks:
      - app-network
    ports:
      - 5183:5183

networks:
  app-network:
    driver: bridge

volumes:
  - logs:./logs
