services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
      args:
        PACKAGE_NAME: '@template-turborepo-vue/web'
    restart: always
    ports:
      - 5173:80

  server:
    container_name: server
    build:
      context: .
      dockerfile: ./apps/server/Dockerfile
      args:
        PACKAGE_NAME: '@template-turborepo-vue/server'
    env_file:
      - ./apps/server/.env
    restart: always
    ports:
      - 5183:5183
