services:
  web:
    image: ${REPOSITORY:-${REPO_NAME}}/web:${TAG:-latest}
    container_name: web
    depends_on:
      - server
    restart: always
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
      args:
        PACKAGE_NAME: '@${REPO_NAME}/web'
        CI: ${CI:-false}
        DO_NOT_TRACK: ${DO_NOT_TRACK:-1}
        TURBO_TEAM: ${TURBO_TEAM}
        TURBO_TOKEN: ${TURBO_TOKEN}
      tags:
        - '${REPOSITORY:-${REPO_NAME}}/web:latest'
    networks:
      - app-network
    ports:
      - 5173:80
    # volumes:
    #   - ./apps/web/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    #   - ./apps/web/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro
    #   - logs:/var/log/nginx

  server:
    image: ${REPOSITORY:-${REPO_NAME}}/server:${TAG:-latest}
    container_name: server
    environment:
      NODE_ENV: production
    env_file:
      - ./apps/server/.env
    restart: always
    build:
      context: .
      dockerfile: ./apps/server/Dockerfile
      args:
        PACKAGE_NAME: '@${REPO_NAME}/server'
        CI: ${CI:-false}
        DO_NOT_TRACK: ${DO_NOT_TRACK:-1}
        TURBO_TEAM: ${TURBO_TEAM}
        TURBO_TOKEN: ${TURBO_TOKEN}
      tags:
        - '${REPOSITORY:-${REPO_NAME}}/server:latest'
    networks:
      - app-network
    ports:
      - 5183:5183

networks:
  app-network:
    driver: bridge

volumes:
  logs:
