packages:
  - apps/*
  - packages/*

shamefullyHoist: true

patchedDependencies:
  plop@4.0.1: patches/plop@4.0.1.patch

allowedDeprecatedVersions:
  glob: '7.2.3'
  inflight: '1.0.6'
  lodash.get: '4.4.2'
  rimraf: '3.0.2'

onlyBuiltDependencies:
  - simple-git-hooks
  - esbuild
  - vue-demi
