services:
  web:
    image: template-turborepo-vue/web:${TAG:-latest}
    container_name: web
    depends_on:
      - server
    restart: always
    networks:
      - app-network
    ports:
      - 5173:80
    # volumes:
    #   - ./nginx/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf:ro
    #   - ./nginx/conf.d:/etc/nginx/conf.d:ro
    #   - logs:/var/log/nginx
    #   - logs:/usr/local/openresty/nginx/logs
    #   - /var/run/openresty

  server:
    image: template-turborepo-vue/server:${TAG:-latest}
    container_name: server
    env_file:
      - .env
    restart: always
    networks:
      - app-network
    ports:
      - 5183:5183

networks:
  app-network:
    driver: bridge

volumes:
  logs:
