name: ${REPO_NAME}

services:
  web:
    image: ${REPOSITORY:-${COMPOSE_PROJECT_NAME}}/web:${TAG:-latest}
    container_name: web
    depends_on:
      - server
    restart: always
    networks:
      - app-network
    ports:
      - 5173:80
    # volumes:
    #   - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    #   - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro
    #   - logs:/var/log/nginx

  server:
    image: ${REPOSITORY:-${COMPOSE_PROJECT_NAME}}/server:${TAG:-latest}
    container_name: server
    env_file:
      - server.env
    restart: always
    networks:
      - app-network
    ports:
      - 5183:5183

networks:
  app-network:
    driver: bridge

volumes:
  logs:
