name: CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  unit-test:
    runs-on: ubuntu-latest
    if: (github.event_name == 'push' && github.event_name != 'pull_request') || github.event_name == 'pull_request'
    env:
      PUPPETEER_SKIP_DOWNLOAD: 'true'
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ vars.TURBO_TEAM }}
    strategy:
      matrix:
        node: [22]
    steps:
      - uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: 'pnpm'

      - name: Install dependencies
        # The --no-lockfile flag is used solely for build demonstration purposes in this template project.
        # Make sure to remove it in your actual project, and ensure that pnpm-lock.yaml is not listed in .gitignore.
        run: pnpm install --no-lockfile

      - name: Run test
        run: pnpm test

      - name: Run build
        run: pnpm build
