name: Publish GitHub Container Registry

on:
  push:
    tags:
      - 'v*'

env:
  REGISTRY: ghcr.io # GitHub Container Registry
  REPO_NAME: ${{ github.event.repository.name }}
  REPO_NAME_FULL: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Extract Dockerized Services
        id: extract-services
        run: |
          SERVICES=$(docker compose config --services)
          echo "services=$(echo $SERVICES | tr '\n' ' ')" >> $GITHUB_OUTPUT
        env:
          COMPOSE_FILE: docker-compose.yml

      - name: Get Version Tag
        id: tag
        run: |
          RAW_TAG=${{ github.ref_name }}
          CLEAN_TAG=${RAW_TAG#v}
          echo "tag=$CLEAN_TAG" >> $GITHUB_OUTPUT
          echo "TAG=$CLEAN_TAG" >> $GITHUB_ENV
          echo "Using tag: $CLEAN_TAG"

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Images
        run: |

          docker compose build
          docker image ls

      - name: Push Images
        run: |
          for SERVICE in ${{ steps.extract-services.outputs.services }}; do
            LOCAL_IMAGE_TAG=${{ env.REPO_NAME }}/$SERVICE:$TAG

            IMAGE="${{ env.REGISTRY }}/${{ env.REPO_NAME_FULL }}/$SERVICE"

            docker tag $LOCAL_IMAGE_TAG $IMAGE:latest
            docker tag $LOCAL_IMAGE_TAG $IMAGE:$TAG
            
            docker push $IMAGE:latest
            docker push $IMAGE:$TAG

            docker rmi -f $LOCAL_IMAGE_TAG
          done

          docker image ls
