name: Publish GitHub Container Registry

on:
  push:
    tags:
      - 'v*'

env:
  REGISTRY: ghcr.io
  REPO_NAME: ${{ github.event.repository.name }}
  IMG_PREFIX: ghcr.io/${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Get Version Tag
        id: tag
        run: |
          RAW_TAG=${{ github.ref_name }}
          CLEAN_TAG=${RAW_TAG#v}
          echo "tag=$CLEAN_TAG" >> $GITHUB_OUTPUT
          echo "TAG=$CLEAN_TAG" >> $GITHUB_ENV
          echo "Using tag: $CLEAN_TAG"

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        env:
          COMPOSE_FILE: docker-compose.yml

      - name: Build Images
        run: |
          docker compose build
          docker image ls

      - name: Push Images
        run: docker compose push
